config/routes.rb
require 'sidekiq/web'
require 'sidekiq-scheduler/web'

Rails.application.routes.draw do
  resources :clients do
    namespace :stagegear do
      resources :projector_rentals do
        namespace :stagegear do
          resources :check_ins
        end
      end
    end
  end

  namespace :api, defaults: { format: :json }, format: false do
    namespace :v2 do
      jsonapi_resources :projector_types
      resources :projector_requests do
        collection do
          put 'cancel'
        end
      end
    end
  end
  
  namespace :stagegear do
    resources :projectors
    resources :projector_rentals do
      member do
        patch :confirm
        put :confirm
      end
    end
    resources :check_ins
  end
end

app/models/stagegear.rb
module StageGear
  def self.table_name_prefix
    "stagegear_"
  end
end

app/models/stagegear/check_in.rb
class StageGear::CheckIn < ApplicationRecord
  belongs_to :projector_rental, optional: true

  validates :projector_rental_id, presence: true, on: :create
  validates :return_date, presence: true

  has_many_attached :images

  enum result: %i[accepted maintenance]

  before_save :update_projector_and_projector_rental_status
  before_save :update_late_return_status

  validate :return_date_cannot_be_in_the_future

  validates :damage_fees, presence: true, if: :damage_description
  validates :late_fee, presence: true, if: :late_return

  private

  def update_projector_and_projector_rental_status
    self.projector_rental.update(status: :completed)

    if self.result == 0
      self.projector_rental.projector.update(status: :available)
    else
      self.projector_rental.projector.update(status: :maintenance)
    end
  end

  def update_late_return_status
    self.late_return = self.return_date > self.projector_rental.end_date
  end

  def return_date_cannot_be_in_the_future
    if return_date.present? && return_date > Date.today
      errors.add(:return_date, "can't be in the future")
    end
  end
end

app/models/stagegear/projector.rb
class StageGear::Projector < ApplicationRecord
  belongs_to :projector_type

  has_many :projector_rentals, dependent: :destroy

  validates :status, presence: true
  validates :unit_number, presence: true
  validates :serial_number, presence: true

  has_many_attached :images
  has_one_attached :thumbnail_image

  enum status: %i[available reserved rented_out maintenance]

  def self.available_on_dates(start_date, end_date)
    self.where.not(
      id:
        StageGear::ProjectorRental.where(
          "start_date <= ? AND end_date >= ? OR start_date <= ? AND end_date >= ? OR start_date > ? AND end_date < ?",
          start_date,
          start_date,
          end_date,
          end_date,
          start_date,
          end_date
        ).pluck(:projector_id)
    )
  end

  def measurements
    self.projector_type.to_json
  end

  def self.available
    # Query for projectors that do not have any associated projector_rentals
    # with a start_date in the future or a status of 'rented'
    StageGear::Projector
      .left_outer_joins(:projector_rentals)
      .where("projector_rentals.start_date > ? OR projector_rentals.status != ?", Date.today, 2)
      .group(:id)
      .having("COUNT(projector_rentals.id) = 0")
  end
end

app/models/stagegear/projector_rental.rb
class StageGear::ProjectorRental < ApplicationRecord
  belongs_to :client
  belongs_to :projector

  has_one_attached :purchase_order

  has_one :check_in, dependent: :nullify

  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :status, presence: true

  validate :start_date_must_be_in_future, on: :create
  validate :projector_not_already_rented, on: %i[create update]
  validate :start_date_is_monday
  validate :end_date_is_monday

  serialize :address, Hash

  enum status: %i[pending reserved active completed cancelled]

  require "shippo"

  def new_rental_with_projector(projector_rental_params)
    projector_type = projector_rental_params[:projector_type]
    start_date = projector_rental_params[:start_date]
    end_date = projector_rental_params[:end_date]

    available_projectors =
      StageGear::Projector.where(
        projector_type: StageGear::ProjectorType.find_by(name: projector_type.capitalize())
      ).available_on_dates(start_date, end_date)

    best_available_projector = available_projectors.first
    raise "No Available Projectors of that type for selected dates" unless best_available_projector

    projector_rental_params[:projector_id] = best_available_projector.id
    projector_rental_params[:address] ||= {}
    projector_rental_params[:address][:country] = "US"

    new(projector_rental_params)
  end

  def order_shipped
    self.update(status: 2)
    self.projector.update(status: :rented_out)
  end

  def order_confirmation
    self.update(status: 1)
    self.projector.update(status: :reserved)
    projector_rental = self
    response =
      projector_rental.create_shippo_request(projector_rental.client, projector_rental.projector)
    if response.status == "SUCCESS"
      pp(response)
      self.update(shippo_object_id: response.object.id)
    else
      render json: response.status, status: :unprocessable_entity
    end
  end

  def create_shippo_request(user, projector)
    shipment_address = {}

    if self.address.present?
      shipment_address = self.address
      shipment_address.merge!(phone_number: "")
    elsif user.address.present?
      shipment_address = user.address
      shipment_address.merge!(street_address: user.address.line1)
      shipment_address.merge!(phone_number: user.phone.number)
    else
      raise "No Address Available for Shipment Creation"
    end

    params = {
      async: false,
      address_from: {
        name: "Stage Gear LLC",
        company: "Stage Gear LLC",
        street1: "402 W. Bedford Suite 101",
        street2: "",
        city: "Fresno",
        state: "CA",
        zip: "93711",
        country: "US",
        phone: ""
      },
      address_to: {
        name: shipment_address["first_name"] + " " + shipment_address["last_name"],
        company: shipment_address["organization"],
        street1: shipment_address["street_address"],
        city: shipment_address["city"],
        state: shipment_address["state"],
        zip: shipment_address["postal_code"],
        country: "US",
        phone: shipment_address["phone_number"],
        email: shipment_address["email"]
      },
      parcels: {
        length: projector.projector_type.length,
        width: projector.projector_type.width,
        height: projector.projector_type.height,
        distance_unit: :in,
        weight: projector.projector_type.weight,
        mass_unit: :lb
      }
    }

    # Make our API call
    shipment = Shippo::Shipment.create(params)

    shipment
  end

  def shippo_order_page
    return "https://apps.goshippo.com/orders/#{self.shippo_object_id}"
  end

  def shippo_order_object
    transaction = Shippo::Shipment.get(self.shippo_object_id)
    transaction
  end

  def tracking_status
    self.shippo_order_object.tracking_status
  end

  def rental_length
    (end_date - start_date) / 7.0
  end

  private

  def start_date_must_be_in_future
    if start_date && start_date < 7.days.from_now
      errors.add(:start_date, "must be more than 7 days away")
    end
  end

  def projector_not_already_rented
    if status == "pending" && projector && projector_already_rented?
      errors.add(:projector, "is already rented during this time period")
    end
  end

  def projector_already_rented?
    projector.projector_rentals.any? do |r|
      r.start_date <= end_date && r.end_date >= end_date ||
        r.start_date <= start_date && r.end_date >= start_date ||
        start_date < r.start_date && end_date > r.end_date
    end
  end

  def start_date_is_monday
    errors.add(:start_date, "must be a Monday") unless start_date.present? && start_date.monday?
  end

  def end_date_is_monday
    errors.add(:end_date, "must be a Monday") unless end_date.present? && end_date.monday?
  end
end

app/models/stagegear/projector_request.rb
class StageGear::ProjectorRequest
  include ActiveModel::API

  attr_accessor :projector_type,
                :start_date,
                :end_date,
                :first_name,
                :last_name,
                :organization,
                :email,
                :street_address,
                :city,
                :state,
                :postal_code,
                :payment_type,
                :coi,
                :drivers_license,
                :purchase_order,
                :success_url,
                :cancel_url

  def create_or_find_client
    Client.find_or_create_by!(email: email) do |c|
      c.assign_attributes(
        first_name: first_name,
        last_name: last_name,
        organization: organization,
        password: "password"
      )
    end
  end

  def find_best_projector
    type = StageGear::ProjectorType.find_by(name: projector_type.capitalize)
    available_projectors =
      StageGear::Projector.where(projector_type: type).available_on_dates(start_date, end_date)
    available_projectors.first
  end

  def create_rental(client, projector)
    rental =
      StageGear::ProjectorRental.new(
        start_date: Date.strptime(start_date),
        end_date: Date.strptime(end_date),
        client: client,
        projector: projector,
        address: {
          "first_name" => first_name,
          "last_name" => last_name,
          "organization" => organization,
          "street_address" => street_address,
          "city" => city,
          "state" => state,
          "postal_code" => postal_code,
          "country" => "US",
          "email" => email
        }
      )
    rental.purchase_order << purchase_order if purchase_order.present?
    rental
  end
end

app/models/stagegear/projector_type.rb
class StageGear::ProjectorType < ApplicationRecord
  has_many :projectors, dependent: :restrict_with_error

  validates :name, presence: true
  validates :length, presence: true
  validates :width, presence: true
  validates :height, presence: true
  validates :weight, presence: true
end

app/controllers/stagegear/check_ins_controller.rb
class StageGear::CheckInsController < BackstageController
  before_action :set_check_in, only: %i[show update]
  before_action :set_rental, only: %i[new]

  def index
    @check_ins = StageGear::CheckIn.all
  end

  def show
    render :show
  end

  def new
    @check_in = StageGear::CheckIn.new
  end

  def create
    @check_in = StageGear::CheckIn.new(check_in_params)

    if @check_in.save
      #render json: @check_in, status: :created, location: @check_in
      redirect_to "/stagegear/check_ins"
    else
      render json: @check_in.errors, status: :unprocessable_entity
    end
  end

  def edit
    @check_in
  end

  def update
    if @check_in.update(check_in_params)
      redirect_to @check_in
    else
      render json: @check_in.errors, status: :unprocessable_entity
    end
  end

  private

  def set_check_in
    @check_in = StageGear::CheckIn.find(params[:id])
  end

  def set_rental
    @rental = StageGear::ProjectorRental.find(params[:projector_rental_id])
  end

  # Date should be "day yyyy-mm-dd"
  def check_in_params
    params.require(:stagegear_check_in).permit(
      :projector_rental_id,
      :status_summary,
      :damage_present,
      :damage_description,
      :damage_fees,
      :return_date,
      :late_return,
      :late_fee,
      :lamp_hours,
      :result,
      images: []
    )
  end
end

app/controllers/stagegear/projector_rentals_controller.rb
class StageGear::ProjectorRentalsController < BackstageController
  before_action :set_client, only: %i[new]
  before_action :set_projector_rental, only: %i[show edit update destroy]

  # GET /projector_rentals
  def index
    @projector_rentals = StageGear::ProjectorRental.all
    @projector_rentals
  end

  # GET /projector_rentals/1
  def show
    @projector_rental.projector
  end

  # GET /projector_rentals/new
  def new
    @projector_rental = StageGear::ProjectorRental.new
  end

  # GET /projector_rentals/1/edit
  def edit
  end

  # POST /projector_rentals
  def create
    @projector_rental = StageGear::ProjectorRental.new_with_projector(projector_rental_params)

    if @projector_rental.save
      redirect_to @projector_rental, notice: "Projector rental was successfully created."
    else
      render :new
    end
  end

  # PATCH/PUT /projector_rentals/1
  def update
    if @projector_rental.update(projector_rental_params)
      redirect_to @projector_rental, notice: "Projector rental was successfully updated."
    else
      render :edit
    end
  end

  # DELETE /projector_rentals/1
  def destroy
    redirect_to projector_rentals_url, notice: "Projector rental was successfully destroyed."
  end

  # Custom controllers for html Views:
  #-------------------------------------------------------------
  def confirm
    rental = StageGear::ProjectorRental.find(params[:id])
    if rental.status == "pending"
      rental.order_confirmation
    elsif rental.status == "reserved"
      rental.order_shipped
    end
    redirect_back(fallback_location: root_path, notice: "Projector rental status updated.")
  end

  private

  def set_client
    @client = Client.find(params[:client_id])
  end
  # Use callbacks to share common setup or constraints between actions.
  def set_projector_rental
    @projector_rental = StageGear::ProjectorRental.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def projector_rental_params
    params.require(:stagegear_projector_rental).permit(
      :start_date,
      :end_date,
      :client_id,
      :projector_type,
      :projector_id,
      :purchase_order,
      address: {
      }
    )
  end
end

app/controllers/stagegear/projectors_controller.rb
class StageGear::ProjectorsController < BackstageController
  before_action :set_projector, only: %i[show update destroy edit]

  def index
    @projectors = StageGear::Projector.order(unit_number: :desc)
    @projectors
  end

  def show
    @projector
  end

  def new
    @projector = StageGear::Projector.new
  end

  def create
    @projector = StageGear::Projector.new(projector_params)

    if @projector.save
      params[:images].each { |image| @projector.images.attach(image) } if params[:images].present?
      redirect_to "StageGear/projectors"
    else
      @projector.errors
    end
  end

  def update
    if @projector.update(projector_params)
      @projector.image.attach(params[:images]) if params[:images].present?
      redirect_to @projector
    else
      render json: @projector.errors, status: :unprocessable_entity
    end
  end

  def edit
    @projector
  end

  # DELETE /projectors/1
  def destroy
    @projector
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_projector
    @projector = StageGear::Projector.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def projector_params
    params.require(:stagegear_projector).permit(
      :projector_type,
      :status,
      :unit_number,
      :manual,
      :serial_number,
      :lens_serial_number,
      :thumbnail_image
    )
  end
end

app/views/stagegear/projector_rentals/_form.html.erb
<%= form_with model:projector_rental, class: "row g-3" do |form| %>
  <% if projector_rental.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(projector_rental.errors.count, "error") %> prohibited this projector_rental from being saved:</h2>

      <ul>
        <% projector_rental.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col-md-6">
    <%= form.label :start_date, class: "form-label" %>
    <%= form.date_field :start_date, class: "form-control" %>
  </div>

  <div class="col-md-6">
    <%= form.label :end_date, class: "form-label" %>
    <%= form.date_field :end_date, class: "form-control" %>
  </div>
  
  <div class="col-md-6">
    <%= form.label :client_id, value: "Client:", class: "form-label" %>
    <%= form.hidden_field :client_id, value: @client.id %>
    <%= @client.name%>
  </div>

  <div class="col-md-6">
    <%= form.label :projector_type, class: "form-label" %>
    <%= form.collection_select :projector_type, ["lite", "economy", "basic", "plus", "premium" ], :to_s , :to_s, class: "form-control" %>
  </div>
  

<h4> Address </h4>
    <div class="col-md-6">
    <%= form.label :address_first_name, "First Name", class: "form-label" %>
    <%= form.text_field :address, name: "stagegear_projector_rental[address][first_name]", class: "form-control" %>
  </div>
  <!-- Add the remaining fields similarly -->
  <div class="col-md-6">
    <%= form.label :address_last_name, "Last Name", class: "form-label" %>
    <%= form.text_field :address, name: "stagegear_projector_rental[address][last_name]", class: "form-control" %>
  </div>

  <div class="col-md-6">
    <%= form.label :address_organization, "Organization", class: "form-label" %>
    <%= form.text_field :address, name: "stagegear_projector_rental[address][organization]", class: "form-control" %>
  </div>

  <div class="col-md-6">
    <%= form.label :address_email, "Email", class: "form-label" %>
    <%= form.email_field :address, name: "stagegear_projector_rental[address][email]", class: "form-control" %>
  </div>

  <div class="col-md-6">
    <%= form.label :address_street_address, "Street Address", class: "form-label" %>
    <%= form.text_field :address, name: "stagegear_projector_rental[address][street_address]", class: "form-control" %>
  </div>

  <div class="col-md-6">
    <%= form.label :address_city, "City", class: "form-label" %>
    <%= form.text_field :address, name: "stagegear_projector_rental[address][city]", class: "form-control" %>
  </div>

  <div class="col-md-6">
    <%= form.label :address_state, "State", class: "form-label" %>
    <%= form.text_field :address, name: "stagegear_projector_rental[address][state]", class: "form-control" %>
  </div>

   <div class="col-md-6">
    <%= form.label :address_postal_code, "Postal Code", class: "form-label" %>
    <%= form.text_field :address, name: "stagegear_projector_rental[address][postal_code]", class: "form-control" %>
  </div>

  <div class="col-md-6">
    <%= form.label :address_country, "Country", class: "form-label" %>
    <%= form.text_field :address, name: "stagegear_projector_rental[address][country]", class: "form-control" %>
  </div>

  <div class="col-12">
    <h5>Upload Purchase Order</h5>
    <%= form.file_field :purchase_order, direct_upload: true, class: "form-control" %>
  </div>

  <br>
  <div class="col-12 text-end">
    <%= form.submit %>
  </div>
<% end %>

app/views/stagegear/projector_rentals/_projector_rental.html.erb
<div id="<%= dom_id projector_rental %>">
  <p>
    <strong>Start date:</strong>
    <%= projector_rental.start_date %>
  </p>

  <p>
    <strong>End date:</strong>
    <%= projector_rental.end_date %>
  </p>

  <p>
    <strong>User:</strong>
    <%= User.find_by(id: projector_rental.client_id).first_name %>
  </p>

  <p>
    <strong>Projector:</strong><br>
    unit_number:
    <%= StageGear::Projector.find_by(id: projector_rental.projector_id).unit_number %><br>
    type:
    <%= StageGear::Projector.find_by(id: projector_rental.projector_id).projector_type.name%>
  </p>
  <p>
    <strong>Status:</strong>
    <%= projector_rental.status %>
  </p>
  <p>
  <strong> Address</strong><br>
    Name: <%= projector_rental.address["first_name"]%> <%= projector_rental.address["last_name"]%><br>
    Organization: <%= projector_rental.address["organization"]%><br>
    E-Mail: <%= projector_rental.address["email"]%><br>
    Street Address <%= projector_rental.address["street_address"]%><br>
    City: <%= projector_rental.address["city"]%><br>
    State: <%= projector_rental.address["state"]%><br>
    Postal Code: <%= projector_rental.address["postal_code"]%>
  </p>
  

  
</div>

app/views/stagegear/projector_rentals/_rental_adjustment.html.erb
<%= form_with model:projector_rental, class: "row g-3" do |form| %>
  <% if projector_rental.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(projector_rental.errors.count, "error") %> prohibited this projector_rental from being saved:</h2>

      <ul>
        <% projector_rental.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col-md-6">
    <%= form.label :start_date, class: "form-label" %>
    <%= form.date_field :start_date, class: "form-control" %>
  </div>

  <div class="col-md-6">
    <%= form.label :end_date, class: "form-label" %>
    <%= form.date_field :end_date, class: "form-control" %>
  </div>
  
  <div class="col-md-6">
    <%= form.label :client_id, value: "Client:", class: "form-label" %>
    <%= form.hidden_field :client_id, value: projector_rental.client.id %>
    <%= projector_rental.client.name%>
  </div>

  <div class="col-md-6">
    <%= form.label :projector_id, class: "form-label" %>
    <%= form.collection_select :projector_id, StageGear::Projector.where(
      projector_type: projector_rental.projector.projector_type
      ).where.not(
        projector_rentals: StageGear::ProjectorRental.where(
          'start_date <= ? AND end_date >= ? OR start_date <= ? AND end_date >= ? OR start_date > ? AND end_date < ?',  projector_rental.start_date, projector_rental.start_date, projector_rental.end_date, projector_rental.end_date, projector_rental.start_date, projector_rental.end_date
          )).map{
          |pr| ["#{pr.unit_number}- #{pr.projector_type.name} ", pr.id] 
          }, :second, :first,  :prompt => true, class: "form-control" %>
  </div>

  <h4> Address </h4>
    <div class="col-md-6">
    <%= form.label :address_first_name, "First Name", class: "form-label" %>
    <%= form.text_field :address, value: projector_rental.address["first_name"], name: "stagegear_projector_rental[address][first_name]", class: "form-control" %>
  </div>
  <!-- Add the remaining fields similarly -->
  <div class="col-md-6">
    <%= form.label :address_last_name, "Last Name", class: "form-label" %>
    <%= form.text_field :address, value: projector_rental.address["last_name"], name: "stagegear_projector_rental[address][last_name]", class: "form-control" %>
  </div>

  <div class="col-md-6">
    <%= form.label :address_organization, "Organization", class: "form-label" %>
    <%= form.text_field :address, value: projector_rental.address["organization"], name: "stagegear_projector_rental[address][organization]", class: "form-control" %>
  </div>

  <div class="col-md-6">
    <%= form.label :address_email, "Email", class: "form-label" %>
    <%= form.email_field :address, value: projector_rental.address["email"], name: "stagegear_projector_rental[address][email]", class: "form-control" %>
  </div>

  <div class="col-md-6">
    <%= form.label :address_street_address, "Street Address", class: "form-label" %>
    <%= form.text_field :address, value: projector_rental.address["street_address"], name: "stagegear_projector_rental[address][street_address]", class: "form-control" %>
  </div>

  <div class="col-md-6">
    <%= form.label :address_city, "City", class: "form-label" %>
    <%= form.text_field :address, value: projector_rental.address["city"], name: "stagegear_projector_rental[address][city]", class: "form-control" %>
  </div>

  <div class="col-md-6">
    <%= form.label :address_state, "State", class: "form-label" %>
    <%= form.text_field :address, value: projector_rental.address["state"], name: "stagegear_projector_rental[address][state]", class: "form-control" %>
  </div>

   <div class="col-md-6">
    <%= form.label :address_postal_code, "Postal Code", class: "form-label" %>
    <%= form.text_field :address, value: projector_rental.address["postal_code"], name: "stagegear_projector_rental[address][postal_code]", class: "form-control" %>
  </div>

<br>
  <div class="col-12 text-end">
    <%= form.submit %>
  </div>
<% end %>

app/views/stagegear/projector_rentals/_table.html.erb
<table class="table table-striped">

  <thead>
    <tr>
      <th>Client</th>
      <th>Projector</th>
      <th>Order Number</th>
      <th>Usage Period</th>
      <th>Status</th>
    </tr>
  </thead>
  <tbody>
    <% if rentals %>
      <% rentals.reverse_each.each do |rental| %>
        <tr>
          <td>
            <div><%= link_to rental.client.name, rental.client %></div>
            <div><%= rental.client.email %></div>
            <div><%= rental.client.organization %></div>
          </td>
          <td>
              <div><%= link_to rental.projector.unit_number, rental.projector %></div>
              <div><%= rental.projector.projector_type.name %></div>
          <td><div><%= rental.order_number %></div></td>
          <td>
            <div>
              <%= rental.start_date.strftime "%b %d %Y" %> - 
              <%= rental.end_date.strftime "%b %d %Y" %>
            </div>
          </td>
          <td>
            <%= rental.status %>
          </td>
          <td>
            <div class="dropdown">
              <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown">
                Actions
              </button>
              <ul class="dropdown-menu">
                <% if rental.status == "pending" %>
                  <li>
                    <%= link_to "Confirm Order and Reserve", confirm_stagegear_projector_rental_path(rental), method: :patch, class: "dropdown-item",
                    data: {confirm: "This will reserve the associated projector and create a Shipment order and label."} %>

                  </li>
                  <% elsif rental.status == "reserved" %>
                  <li>
                    <%= link_to "Shippo Order Page", url_for(rental.shippo_order_page), :target => "_blank", class: "dropdown-item" %>
                  </li>
                  <li>
                    <%= link_to "Confirm Shipment", confirm_stagegear_projector_rental_path(rental),  method: :patch, class: "dropdown-item", 
                    data: {confirm: "Mark the rental and projector as Shipped?"}%>
                  </li>  
                  <% elsif rental.status == "active" %>
                  <li>
                    <%= link_to "Shippo Order Page", url_for(rental.shippo_order_page), :target => "_blank", class: "dropdown-item" %>
                  </li>
                    <li>
                    <%= link_to "Check In", new_stagegear_check_in_path(projector_rental_id: rental.id), class: "dropdown-item" %>
                  </li>
                <% end %>
                <li>
                  <%= link_to "Edit", [:edit, @projector_rental, rental], class: "dropdown-item" %>
                </li>
                <li>
                  <%= link_to "Delete", [@projector_rental, rental], method: :delete, class: "dropdown-item text-danger",
                  data: {confirm: "Are you sure you want to delete this rental?"} %>
                </li>
              </ul>
            </div>
          </td>

        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/stagegear/projector_rentals/edit.html.erb
<h1>Editing Projector Rental</h1>

<%= render "rental_adjustment", projector_rental: @projector_rental %>

<br>

<div>
  <%= link_to "Show this projector_rental", @projector_rental %> |
  <%= link_to "Back to projector_rentals", stagegear_projector_rentals_path %>
</div>

app/views/stagegear/projector_rentals/index.html.erb
<% content_for(:title) { "Projector_rentals" } %>
<% content_for(:breadcrumbs) do %>
  <li class="breadcrumb-item active" aria-current="page">
    Projector_Rentals
  </li>
<% end %>
<div><%= link_to "Projectors", :stagegear_projectors %> | <%= link_to "Check Ins", :stagegear_check_ins %></div>
<h2>ProjectorRentals</h2>
<button class="btn btn-secondary" onclick="openPage('all', this, 'white')">All</button>
<button class="btn btn-secondary" onclick="openPage('pending', this, 'white')" id="defaultOpen">Pending</button>
<button class="btn btn-secondary" onclick="openPage('reserved', this, 'white')">Reserved</button>
<button class="btn btn-secondary" onclick="openPage('active', this, 'white')">Active</button>
<button class="btn btn-secondary" onclick="openPage('past', this, 'white')">Past</button>
<br><br>

<div id="all" class="tabcontent">
<h3>All Rentals</h3>
<%= render "table", rentals: @projector_rentals %>
</div>

<div id="pending" class="tabcontent">
<h3>Pending Rentals</h3>
<%= render "table", rentals: @projector_rentals.where(status: 'pending') %>
</div>

<div id="reserved" class="tabcontent">
<h3>Reserved Rentals</h3>
<%= render "table", rentals: @projector_rentals.where(status: 'reserved') %>
</div>

<div id="active" class="tabcontent">
<h3>Active Rentals</h3>
<%= render "table", rentals: @projector_rentals.where(status: 'active') %>
</div>

<div id="past" class="tabcontent">
<h3>Past Rentals</h3>
<%= render "table", rentals: @projector_rentals.where(status: 'completed') %>
</div>


<script>
function openPage(pageName,elmnt,color) {
  var i, tabcontent, tablinks;
  tabcontent = document.getElementsByClassName("tabcontent");
  for (i = 0; i < tabcontent.length; i++) {
    tabcontent[i].style.display = "none";
  }
  tablinks = document.getElementsByClassName("tablink");
  for (i = 0; i < tablinks.length; i++) {
    tablinks[i].style.backgroundColor = "";
  }
  document.getElementById(pageName).style.display = "block";
}

// Get the element with id="defaultOpen" and click on it
document.getElementById("defaultOpen").click();
</script>

app/views/stagegear/projector_rentals/new.html.erb
<h1>New projector_rental</h1>

<%= render "form", projector_rental: @projector_rental %>

<br>

<div>
  <%= link_to "Back to projector_rentals", stagegear_projector_rentals_path %>
</div>

app/views/stagegear/projector_rentals/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @projector_rental %>

<% if @projector_rental.purchase_order.attached? %>
  <p>
    <%= link_to "View Purchase Order", rails_blob_path(@projector_rental.purchase_order, disposition:'attachment') %>
  </p>
<%end%>

<% #@shipment = @projector_rental.tracking_status %>
<div>
  <p><%= link_to "Edit this Rental", edit_stagegear_projector_rental_path(@projector_rental), class:"btn btn-secondary" %><br><br> 
  <%= link_to "Back to Rentals", stagegear_projector_rentals_path, class:"btn btn-secondary" %></p>
</div>