config/routes.rb
require 'sidekiq/web'
require 'sidekiq-scheduler/web'

Rails.application.routes.draw do
  resources :clients do
    namespace :stagegear do
      resources :projector_rentals do
        namespace :stagegear do
          resources :check_ins
        end
      end
    end
  end

  namespace :api, defaults: { format: :json }, format: false do
    namespace :v2 do
      jsonapi_resources :projector_types
      resources :projector_requests do
        collection do
          put 'cancel'
        end
      end
    end
  end
  
  namespace :stagegear do
    resources :projectors
    resources :projector_rentals do
      member do
        patch :confirm
        put :confirm
      end
    end
    resources :check_ins
  end
end

app/models/stagegear.rb
module StageGear
  def self.table_name_prefix
    "stagegear_"
  end
end

app/models/stagegear/check_in.rb
class StageGear::CheckIn < ApplicationRecord
  belongs_to :projector_rental, optional: true

  validates :projector_rental_id, presence: true, on: :create
  validates :return_date, presence: true

  has_many_attached :images

  enum result: %i[accepted maintenance]

  before_save :update_projector_and_projector_rental_status
  before_save :update_late_return_status

  validate :return_date_cannot_be_in_the_future

  validates :damage_fees, presence: true, if: :damage_description
  validates :late_fee, presence: true, if: :late_return

  private

  def update_projector_and_projector_rental_status
    self.projector_rental.update(status: :completed)

    if self.result == 0
      self.projector_rental.projector.update(status: :available)
    else
      self.projector_rental.projector.update(status: :maintenance)
    end
  end

  def update_late_return_status
    self.late_return = self.return_date > self.projector_rental.end_date
  end

  def return_date_cannot_be_in_the_future
    if return_date.present? && return_date > Date.today
      errors.add(:return_date, "can't be in the future")
    end
  end
end

app/models/stagegear/projector.rb
class StageGear::Projector < ApplicationRecord
  belongs_to :projector_type

  has_many :projector_rentals, dependent: :destroy

  validates :status, presence: true
  validates :unit_number, presence: true
  validates :serial_number, presence: true

  has_many_attached :images
  has_one_attached :thumbnail_image

  enum status: %i[available reserved rented_out maintenance]

  def self.available_on_dates(start_date, end_date)
    self.where.not(
      id:
        StageGear::ProjectorRental.where(
          "start_date <= ? AND end_date >= ? OR start_date <= ? AND end_date >= ? OR start_date > ? AND end_date < ?",
          start_date,
          start_date,
          end_date,
          end_date,
          start_date,
          end_date
        ).pluck(:projector_id)
    )
  end

  def measurements
    self.projector_type.to_json
  end

  def self.available
    # Query for projectors that do not have any associated projector_rentals
    # with a start_date in the future or a status of 'rented'
    StageGear::Projector
      .left_outer_joins(:projector_rentals)
      .where("projector_rentals.start_date > ? OR projector_rentals.status != ?", Date.today, 2)
      .group(:id)
      .having("COUNT(projector_rentals.id) = 0")
  end
end

app/models/stagegear/projector_rental.rb
class StageGear::ProjectorRental < ApplicationRecord
  belongs_to :client
  belongs_to :projector

  has_one_attached :purchase_order

  has_one :check_in, dependent: :nullify

  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :status, presence: true

  validate :start_date_must_be_in_future, on: :create
  validate :projector_not_already_rented, on: %i[create update]
  validate :start_date_is_monday
  validate :end_date_is_monday

  serialize :address, Hash

  enum status: %i[pending reserved active completed cancelled]

  require "shippo"

  def new_rental_with_projector(projector_rental_params)
    projector_type = projector_rental_params[:projector_type]
    start_date = projector_rental_params[:start_date]
    end_date = projector_rental_params[:end_date]

    available_projectors =
      StageGear::Projector.where(
        projector_type: StageGear::ProjectorType.find_by(name: projector_type.capitalize())
      ).available_on_dates(start_date, end_date)

    best_available_projector = available_projectors.first
    raise "No Available Projectors of that type for selected dates" unless best_available_projector

    projector_rental_params[:projector_id] = best_available_projector.id
    projector_rental_params[:address] ||= {}
    projector_rental_params[:address][:country] = "US"

    new(projector_rental_params)
  end

  def order_shipped
    self.update(status: 2)
    self.projector.update(status: :rented_out)
  end

  def order_confirmation
    self.update(status: 1)
    self.projector.update(status: :reserved)
    projector_rental = self
    response =
      projector_rental.create_shippo_request(projector_rental.client, projector_rental.projector)
    if response.status == "SUCCESS"
      pp(response)
      self.update(shippo_object_id: response.object.id)
    else
      render json: response.status, status: :unprocessable_entity
    end
  end

  def create_shippo_request(user, projector)
    shipment_address = {}

    if self.address.present?
      shipment_address = self.address
      shipment_address.merge!(phone_number: "")
    elsif user.address.present?
      shipment_address = user.address
      shipment_address.merge!(street_address: user.address.line1)
      shipment_address.merge!(phone_number: user.phone.number)
    else
      raise "No Address Available for Shipment Creation"
    end

    params = {
      async: false,
      address_from: {
        name: "Stage Gear LLC",
        company: "Stage Gear LLC",
        street1: "402 W. Bedford Suite 101",
        street2: "",
        city: "Fresno",
        state: "CA",
        zip: "93711",
        country: "US",
        phone: ""
      },
      address_to: {
        name: shipment_address["first_name"] + " " + shipment_address["last_name"],
        company: shipment_address["organization"],
        street1: shipment_address["street_address"],
        city: shipment_address["city"],
        state: shipment_address["state"],
        zip: shipment_address["postal_code"],
        country: "US",
        phone: shipment_address["phone_number"],
        email: shipment_address["email"]
      },
      parcels: {
        length: projector.projector_type.length,
        width: projector.projector_type.width,
        height: projector.projector_type.height,
        distance_unit: :in,
        weight: projector.projector_type.weight,
        mass_unit: :lb
      }
    }

    # Make our API call
    shipment = Shippo::Shipment.create(params)

    shipment
  end

  def shippo_order_page
    return "https://apps.goshippo.com/orders/#{self.shippo_object_id}"
  end

  def shippo_order_object
    transaction = Shippo::Shipment.get(self.shippo_object_id)
    transaction
  end

  def tracking_status
    self.shippo_order_object.tracking_status
  end

  def rental_length
    (end_date - start_date) / 7.0
  end

  private

  def start_date_must_be_in_future
    if start_date && start_date < 7.days.from_now
      errors.add(:start_date, "must be more than 7 days away")
    end
  end

  def projector_not_already_rented
    if status == "pending" && projector && projector_already_rented?
      errors.add(:projector, "is already rented during this time period")
    end
  end

  def projector_already_rented?
    projector.projector_rentals.any? do |r|
      r.start_date <= end_date && r.end_date >= end_date ||
        r.start_date <= start_date && r.end_date >= start_date ||
        start_date < r.start_date && end_date > r.end_date
    end
  end

  def start_date_is_monday
    errors.add(:start_date, "must be a Monday") unless start_date.present? && start_date.monday?
  end

  def end_date_is_monday
    errors.add(:end_date, "must be a Monday") unless end_date.present? && end_date.monday?
  end
end

app/models/stagegear/projector_request.rb
class StageGear::ProjectorRequest
  include ActiveModel::API

  attr_accessor :projector_type,
                :start_date,
                :end_date,
                :first_name,
                :last_name,
                :organization,
                :email,
                :street_address,
                :city,
                :state,
                :postal_code,
                :payment_type,
                :coi,
                :drivers_license,
                :purchase_order,
                :success_url,
                :cancel_url

  def create_or_find_client
    Client.find_or_create_by!(email: email) do |c|
      c.assign_attributes(
        first_name: first_name,
        last_name: last_name,
        organization: organization,
        password: "password"
      )
    end
  end

  def find_best_projector
    type = StageGear::ProjectorType.find_by(name: projector_type.capitalize)
    available_projectors =
      StageGear::Projector.where(projector_type: type).available_on_dates(start_date, end_date)
    available_projectors.first
  end

  def create_rental(client, projector)
    rental =
      StageGear::ProjectorRental.new(
        start_date: Date.strptime(start_date),
        end_date: Date.strptime(end_date),
        client: client,
        projector: projector,
        address: {
          "first_name" => first_name,
          "last_name" => last_name,
          "organization" => organization,
          "street_address" => street_address,
          "city" => city,
          "state" => state,
          "postal_code" => postal_code,
          "country" => "US",
          "email" => email
        }
      )
    rental.purchase_order << purchase_order if purchase_order.present?
    rental
  end
end

app/models/stagegear/projector_type.rb
class StageGear::ProjectorType < ApplicationRecord
  has_many :projectors, dependent: :restrict_with_error

  validates :name, presence: true
  validates :length, presence: true
  validates :width, presence: true
  validates :height, presence: true
  validates :weight, presence: true
end

app/controllers/stagegear/check_ins_controller.rb
class StageGear::CheckInsController < BackstageController
  before_action :set_check_in, only: %i[show update]
  before_action :set_rental, only: %i[new]

  def index
    @check_ins = StageGear::CheckIn.all
  end

  def show
    render :show
  end

  def new
    @check_in = StageGear::CheckIn.new
  end

  def create
    @check_in = StageGear::CheckIn.new(check_in_params)

    if @check_in.save
      #render json: @check_in, status: :created, location: @check_in
      redirect_to "/stagegear/check_ins"
    else
      render json: @check_in.errors, status: :unprocessable_entity
    end
  end

  def edit
    @check_in
  end

  def update
    if @check_in.update(check_in_params)
      redirect_to @check_in
    else
      render json: @check_in.errors, status: :unprocessable_entity
    end
  end

  private

  def set_check_in
    @check_in = StageGear::CheckIn.find(params[:id])
  end

  def set_rental
    @rental = StageGear::ProjectorRental.find(params[:projector_rental_id])
  end

  # Date should be "day yyyy-mm-dd"
  def check_in_params
    params.require(:stagegear_check_in).permit(
      :projector_rental_id,
      :status_summary,
      :damage_present,
      :damage_description,
      :damage_fees,
      :return_date,
      :late_return,
      :late_fee,
      :lamp_hours,
      :result,
      images: []
    )
  end
end

app/controllers/stagegear/projector_rentals_controller.rb
class StageGear::ProjectorRentalsController < BackstageController
  before_action :set_client, only: %i[new]
  before_action :set_projector_rental, only: %i[show edit update destroy]

  # GET /projector_rentals
  def index
    @projector_rentals = StageGear::ProjectorRental.all
    @projector_rentals
  end

  # GET /projector_rentals/1
  def show
    @projector_rental.projector
  end

  # GET /projector_rentals/new
  def new
    @projector_rental = StageGear::ProjectorRental.new
  end

  # GET /projector_rentals/1/edit
  def edit
  end

  # POST /projector_rentals
  def create
    @projector_rental = StageGear::ProjectorRental.new_with_projector(projector_rental_params)

    if @projector_rental.save
      redirect_to @projector_rental, notice: "Projector rental was successfully created."
    else
      render :new
    end
  end

  # PATCH/PUT /projector_rentals/1
  def update
    if @projector_rental.update(projector_rental_params)
      redirect_to @projector_rental, notice: "Projector rental was successfully updated."
    else
      render :edit
    end
  end

  # DELETE /projector_rentals/1
  def destroy
    redirect_to projector_rentals_url, notice: "Projector rental was successfully destroyed."
  end

  # Custom controllers for html Views:
  #-------------------------------------------------------------
  def confirm
    rental = StageGear::ProjectorRental.find(params[:id])
    if rental.status == "pending"
      rental.order_confirmation
    elsif rental.status == "reserved"
      rental.order_shipped
    end
    redirect_back(fallback_location: root_path, notice: "Projector rental status updated.")
  end

  private

  def set_client
    @client = Client.find(params[:client_id])
  end
  # Use callbacks to share common setup or constraints between actions.
  def set_projector_rental
    @projector_rental = StageGear::ProjectorRental.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def projector_rental_params
    params.require(:stagegear_projector_rental).permit(
      :start_date,
      :end_date,
      :client_id,
      :projector_type,
      :projector_id,
      :purchase_order,
      address: {
      }
    )
  end
end

app/controllers/stagegear/projectors_controller.rb
class StageGear::ProjectorsController < BackstageController
  before_action :set_projector, only: %i[show update destroy edit]

  def index
    @projectors = StageGear::Projector.order(unit_number: :desc)
    @projectors
  end

  def show
    @projector
  end

  def new
    @projector = StageGear::Projector.new
  end

  def create
    @projector = StageGear::Projector.new(projector_params)

    if @projector.save
      params[:images].each { |image| @projector.images.attach(image) } if params[:images].present?
      redirect_to "StageGear/projectors"
    else
      @projector.errors
    end
  end

  def update
    if @projector.update(projector_params)
      @projector.image.attach(params[:images]) if params[:images].present?
      redirect_to @projector
    else
      render json: @projector.errors, status: :unprocessable_entity
    end
  end

  def edit
    @projector
  end

  # DELETE /projectors/1
  def destroy
    @projector
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_projector
    @projector = StageGear::Projector.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def projector_params
    params.require(:stagegear_projector).permit(
      :projector_type,
      :status,
      :unit_number,
      :manual,
      :serial_number,
      :lens_serial_number,
      :thumbnail_image
    )
  end
end

app/views/stagegear/projectors/_form.html.erb
<%= form_with(model: projector) do |form| %>
  
  <div>
  Projector Type: <%= projector.projector_type.name%>
  </div>


  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.select :status, status: [:available, :reserved, :rented_out, :maintenance] %>
  </div>

  <div>
    <%= form.label :unit_number, style: "display: block" %>
    <%= form.text_field :unit_number %>
  </div>

  <div>
    <%= form.label :serial_number, style: "display: block" %>
    <%= form.text_field :serial_number %>
  </div>

  <div>
    <%= form.label :lens_serial_number, style: "display: block" %>
    <%= form.text_field :lens_serial_number %>
  </div>
  <br>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/stagegear/projectors/_projector.html.erb
<button type="button" class="collapsible">
  <p>Unit <%= projector.unit_number %> |
  Type: <%= projector.projector_type.name %> |
  Status: <%= projector.status %></p>
</button>
<div class="content">
<div class="projector">
  <h4>Unit <%= projector.unit_number %></h4>
  <p>Type: <%= projector.projector_type.name %></p>
  <p>Status: <%= projector.status.capitalize() %></p>
  <p>Serial Number: <%= projector.serial_number %></p>
  <p>Lens Serial Number: <%= projector.lens_serial_number%></p>

  <%= link_to 'Edit', edit_stagegear_projector_path(projector) %>
</div>
</div>

app/views/stagegear/projectors/edit.html.erb
<h3>Editing Projector <%= @projector.unit_number %></h3>

<%= render "form", projector: @projector %>

<br>

<div>
  <%= link_to "Show this projector", stagegear_projector_path %> |
  <%= link_to "Back to projectors", stagegear_projectors_path %>
</div>

app/views/stagegear/projectors/index.html.erb
<style>
.collapsible {
  background-color: #777;
  color: white;
  width: 100%;
  text-align: left;
  margin: 2px;
}

.active1, .collapsible:hover {
  background-color: #555;
}
.btn-secondary{
  margin-top:5px;
}
.content {
  padding: 18px;
  display: none;
  overflow: hidden;
  background-color: #f1f1f1;
}
</style>

<p style="color: green"><%= notice %></p>
<% content_for(:title) { "Projectors" } %>
<% content_for(:breadcrumbs) do %>
  <li class="breadcrumb-item active" aria-current="page">
    Projectors
  </li>
<% end %>
  <div><%= link_to "Rentals", :stagegear_projector_rentals %> | <%= link_to "Check Ins", :stagegear_check_ins %></div>

<h2>Projector Inventory</h2>
<%= link_to "Add New Projector", new_stagegear_projector_path, class: 'btn btn-primary' %>

<div id="projectors"><br>
  <% @projectors.reverse_each do |projector| %>
    <%= render projector %>
  <% end %>
</div>
<br>
<%= link_to "Add New Projector", new_stagegear_projector_path, class: 'btn btn-primary' %>

<script>
var coll = document.getElementsByClassName("collapsible");
var i;

for (i = 0; i < coll.length; i++) {
  coll[i].addEventListener("click", function() {
    this.classList.toggle("active1");
    var content = this.nextElementSibling;
    if (content.style.display === "block") {
      content.style.display = "none";
    } else {
      content.style.display = "block";
    }
  });
}
</script>

app/views/stagegear/projectors/new.html.erb
<h1>New projector</h1>

<%= render "form", projector: @projector %>

<br>

<div>
  <%= link_to "Back to projectors", stagegear_projectors_path %>
</div>

app/views/stagegear/projectors/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @projector %>

<% if @projector.thumbnail_image.attached? %>
<div>
Thumbnail:
<br>
  <%= image_tag @projector.thumbnail_image, :style => ["height:200px" ]%>
  </div>
<% end %>

<% if @projector.images.attached? %>
<div>
Product Images:
  <% @projector.images.each do |image| %>
  <div>
    <%= image_tag image, :style => "height:200px" %>
  </div>
  <% end %>
  </div>
<% end %>

<div>

  <%= link_to "Back to projectors", stagegear_projectors_path %>
  <%= link_to 'Edit Projector', edit_stagegear_projector_path(@projector), class: 'btn btn-primary' %>
  <%= button_to "Destroy this projector", @projector, method: :delete %>
</div>